# Generated by Django 2.1.5 on 2019-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_registration',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Contact_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=30)),
                ('Website', models.CharField(max_length=255)),
            ],
        ),
    ]
